[build]
  command = "npm run build"

[[redirects]]
  from = "https://planifiweb-gateway.netlify.app/*"
  to = "https://planifiweb.guidojh.pro/:splat"
  status = 308
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
